#!/bin/bash
# Flush out the list before we begin
ipfw -q -f flush

# Set rules command prefix
cmd="ipfw -q add"
vpn="mytun"

# allow all local traffic on the loopback interface
$cmd 00001 allow all from any to any via lo0

# allow any connection to/from VPN interface
$cmd 00010 allow all from any to any via $vpn

# allow connection to/from LAN by Deluge
$cmd 00101 allow all from me to IP_ID uid media
$cmd 00102 allow all from IP_ID to me uid media

# deny any Deluge connection outside LAN that does not use VPN
$cmd 00103 deny all from any to any uid media
